const path=require("path"),promise=require("bluebird"),log=require("npmlog"),Table=require("easy-table"),fs=promise.promisifyAll(require("fs-extra")),readJsonSync=require("./util/json").readJsonSync,copyToDirAsync=require("./util/copy").copyToDirAsync,merge=require("./util/merge"),errHndl=require("./base/error-handler");
function Generator(c){function a(g){if(g){const d=path.join(__dirname,"..");g=fs.readFileSync(g);g=g.toString().replace(/\$cli-root/gi,d).replace(/\\/g,"/");h=JSON.parse(g)}else h=null}let h;a(c);this.setTmplates=a;this.getTemplates=function(){return h}}
Generator.prototype.showTemplates=function(c){const a=this.getTemplates(),h=new Table,g={webapp:"Web App",nativeapp:"Native App",webappinfo:"Web App Info",nativeappinfo:"Native App Info",jsservice:"JS Service",jsserviceinfo:"JS Service Info",packageinfo:"Package Info"};for(const d in a){if(!0===a[d].hide||!a[d].type)continue;const l=a[d].default?"(default) ":"",v=a[d].branch||"-",w=g[a[d].type]||a[d].type;c&&-1===["true","false",!0,!1].indexOf(c)&&a[d].type&&null===a[d].type.match(new RegExp(c+"$",
"gi"))||(h.cell("ID",d),h.cell("Project Type",w),h.cell("Version",v),h.cell("Description",l+a[d].description),h.newRow())}console.log(h.print())};Generator.prototype.existOutDir=function(c){log.verbose("Generator#existOutDir()",c);try{if(0<fs.readdirSync(c).length)return!0}catch(a){if(a&&"ENOTDIR"===a.code)throw errHndl.getErrMsg("NOT_DIRTYPE_PATH",c);if(a&&"ENOENT"===a.code)return log.verbose("Generator#existOutDir()","The directory does not exist"),!1;throw a;}};
Generator.prototype.generate=function(c){function a(b,e){b=[].concat(b.path);return promise.all(b.map(function(k){return fs.lstatAsync(k).then(function(n){if(!n.isFile())throw errHndl.getErrMsg("INVALID_PATH","meta template",k);n=fs.readFileSync(k,"utf8");n=n.replace(RegExp("(?:['\"])([:/.A-z?<_&s=>0-9;-]+')"),"'"+e+"'");const x=path.join(t,path.basename(k));fs.writeFileSync(x,n,{encoding:"utf8"})})})).then(function(){log.verbose("Generator#generate()#_writeUrldata():","done")}).catch(function(k){log.verbose("Generator#generate()#_writeUrldata()#err:",
k);throw k;})}function h(b,e,k,n){log.verbose("Generator#generate()#_writeMetadata()");const x=[].concat(b.path),y=e||{},z=k||{},A=n||{};return promise.all(x.map(function(p){return fs.lstatAsync(p).then(function(q){if(!q.isFile())throw errHndl.getErrMsg("INVALID_PATH","meta template",p);q=path.basename(p);let m=readJsonSync(p);"appinfo.json"===q?m=merge(m,y):"services.json"===q?m=merge(m,z):"package.json"===q&&"jsserviceinfo"===b.type?m.name=l.id||m.name:"packageinfo.json"===q&&(m=merge(m,A));return m}).then(function(q){const m=
path.join(t,path.basename(p));return fs.mkdirsAsync(t).then(function(){return fs.writeFileSync(m,JSON.stringify(q,null,2),{encoding:"utf8"})})})})).then(function(){log.verbose("Generator#generate()#_writeMetadata():","done")}).catch(function(p){log.verbose("Generator#generate()#_writeMetadata()#err:",p);throw p;})}const g=c.tmplName,d=c.pkginfo,l=c.svcinfo,v=c.svcName,w=c.out,u=this.getTemplates(),t=path.resolve(w),f=u[g];let r=c.appinfo;if(!f)return promise.reject(errHndl.getErrMsg("INVALID_TEMPLATE"));
f.metadata&&f.metadata.data&&"object"===typeof f.metadata.data&&(r=merge(r,f.metadata.data));v?(l.id=v,l.services=[{name:v}]):!v&&l.id&&(l.services=[{name:l.id}]);return promise.resolve().then(function(){log.verbose("Generator#generate()","template name:"+g);console.log("Generating "+g+" in "+t);let b;if(g.match(/(^hosted)/))return b=[].concat(f.path),promise.all(b.map(function(e){return copyToDirAsync(e,t)})).then(function(){let e,k;f.metadata&&f.metadata.id&&(e=u[f.metadata.id]);if(e){if(r.url){k=
r.url;delete r.url;const n={path:path.join(b[0],"index.html")};a(n,k)}return h(e,r,l,d)}});if(f.type.match(/info$/))return h(f,r,l,d);b=[].concat(f.path);return promise.all(b.map(function(e){log.verbose("Generator#generate()","template src:"+e);return copyToDirAsync(e,t)})).then(function(){let e;f.metadata&&f.metadata.id&&(e=u[f.metadata.id]);if(e)return h(e,r,l,d)})}).then(function(){return promise.all((u[g].deps||[]).map(function(b){if(u[b]){if(u[b].path)return copyToDirAsync(u[b].path,t);log.warn("Generator#generate()",
"Invalid template path "+b)}else log.warn("Generator#generate()","Invalid template id "+b)}))}).then(function(){log.verbose("Generator#generate():","done");return{msg:"Success"}}).catch(function(b){log.verbose("Generator#generate()#err:",b);throw b;})};module.exports=Generator;
