const log=require("npmlog"),async=require("async"),colors=require("colors"),util=require("util"),streamBuffers=require("stream-buffers"),novacom=require("./base/novacom"),hasProperty=require("./util/property"),errHndl=require("./base/error-handler"),msgNotFoundLog="There is no logs",defaultLogFile="/media/developer/log/devlog";
(function(){const p={log,printLog:function(c,m){function n(d){function e(b){log.verbose("log#_checkFilter()");const f="DEBUG INFO WARNING ERR CRIT SILENT".split(" ");let a=!0,g=!0;c.id&&""!==c.id&&(g=c.id===b.id.trim());var h=hasProperty(c.filters,b.tag)?c.filters[b.tag].toUpperCase():c.filters["*"].toUpperCase();h=f.indexOf({D:"DEBUG",I:"INFO",W:"WARNING",E:"ERR",C:"CRIT",S:"SILENT"}[h]);b=f.indexOf(b.level.toUpperCase());if(-1===h||-1===b||h>b)a=!1;log.silly("log#_checkFilter()","filterFlag:",a,
", idFlag:",g);return a&&g}function k(b){log.verbose("log#_printLog()");let f="["+(b.level+"|"+b.tag+"|"+b.id)+"] ";if(0!==b.text.trim().length){if(c.output){const a=c.output.split(":");for(let g=0;g<a.length;g++)"pid"===a[g]&&(f+="["),"tid"===a[g]&&(f+=":"),b[a[g]]&&(f+=b[a[g].toLowerCase()]+" "),"tid"===a[g]&&(f+="] ")}f+=b.text;f=f[{DEBUG:"blue",INFO:"green",WARNING:"yellow",ERR:"red",CRIT:"cyan",SILENT:"gray"}[b.level.toUpperCase()]];console.log(f)}}(Buffer.isBuffer(d)?d.toString():d).split(/\r?\n/).forEach(function(b){log.verbose("log#_onLine()");
if(""!==b&&void 0!==b)if(b===msgNotFoundLog)log.warn(b);else{log.verbose("log#_splitLog()");var f=-1,a={time:"",monotonicTime:"",facility:"",process:"",pid:"",context:"",messageId:""};for(d in a){var g=b.slice(++f).indexOf(" ");a[d]=b.slice(f,f+g);f+=g}a.time=(new Date(a.time)).toString();a.level=a.facility.split(".")[1]||"";a.facility=a.facility.split(".")[0]||"";a.tid=a.pid.slice(1,a.pid.length-1).split(":")[1]||"";a.pid=a.pid.slice(1,a.pid.length-1).split(":")[0]||"";b=b.slice(f);g=b.indexOf("} ");
b=[b.slice(0,g),b.slice(g+1)];a.text=b[b.length-1];a.id="";a.tag="";b=a.text.indexOf("/");g=a.text.indexOf(":");-1!==b&&-1!==g&&b<g&&(a.id=a.text.slice(0,b),a.tag=a.text.slice(b+1,g),a.text=a.text.slice(g+1));log.silly("log#_splitLog()","logObj:",a);c.since&&Date.parse(c.today)<Date.parse(a.time)&&e(a)?(log.silly("log#_onLine()","since:",c.since,", today:",Date.parse(c.today),", log time:",Date.parse(a.time)),k(a)):!c.since&&e(a)&&k(a)}})}function l(d,e){return d?d.match(/^[0-9]+$/)&&0<=d&&("d"===
e||"h"===e||"m"===e||"s"===e)?!0:!1:!1}async.waterfall([function(d){log.verbose("log#_makeSession");c.session=new novacom.Session(c.device,d)}.bind(this),function(d,e){if(c.since){log.verbose("log#_splitTime");d=c.since.toLowerCase();let k,b,f,a;if(0<=d.indexOf("d")&&(k=d.substring(0,d.indexOf("d")),!l(k,"d"))||0<=d.indexOf("h")&&(b=d.substring(d.indexOf("d")+1,d.indexOf("h")),!l(b,"h"))||0<=d.indexOf("m")&&(f=d.substring(d.indexOf("h")+1,d.indexOf("m")),!l(f,"m"))||0<=d.indexOf("s")&&(a=d.substring(d.indexOf("m")+
1,d.indexOf("s")),!l(a,"s")))return log.error(errHndl.getErrMsg("INVALID_VALUE","since",c.since)),e(errHndl.getErrMsg("INVALID_SINCE"));if("true"===c.since)return e(errHndl.getErrMsg("EMPTY_VALUE","since"));const g=new streamBuffers.WritableStreamBuffer;c.session.run("/bin/date +%s",null,g,null,function(){var h=g.getContentsAsString();h=new Date(1E3*h);l(k,"d")&&h.setDate(h.getDate()-k);l(b,"h")&&h.setHours(h.getHours()-b);l(f,"m")&&h.setMinutes(h.getMinutes()-f);l(a,"s")&&h.setSeconds(h.getSeconds()-
a);c.today=h;e(null)})}else e(null)}.bind(this),function(d){var e={};e.since=c.since;e.id=c.id;e.output=c.output;e.filter=c.filter;e.follow=c.follow;e.logFilePath=c.logFilePath;log.verbose("log#_splitArguments()","_options:",e);e="DIWECS".split("");const k={DEFAULT:"",TIME:"time",PROCESS:"time:process:pid:tid"},b={"*":"D"};for(let f=0;f<c.filters.length;f++){const a=c.filters[f].split(":");if(2<a.length||2===a.length&&(""===a[0]||""===a[1])||2===a.length&&-1===e.indexOf(a[1].toUpperCase()))return log.error(errHndl.getErrMsg("INVALID_VALUE",
"FILTER",c.filters[f])),d(errHndl.getErrMsg("INVALID_FILTER"));b[a[0]]=a[1]||"D"}c.filters=b;if(c.output){if("true"===c.output)return d(errHndl.getErrMsg("EMPTY_VALUE","output"));if(hasProperty(k,c.output.toUpperCase()))c.output=k[c.output.toUpperCase()];else return log.error(errHndl.getErrMsg("INVALID_VALUE","output",c.output)),d(errHndl.getErrMsg("INVALID_LOG_OUTPUT"))}d(null)}.bind(this),function(d){log.verbose("log#_getLogs()");const e=c.logFilePath||defaultLogFile;async.series([function(k){const b=
util.format("test -e %s && ( wc -l %s | xargs tail %s -n ) || echo %s",e,e,c.follow,msgNotFoundLog);log.verbose("log#_getLogs()","cmd: ",b);c.session.run(b,process.stdin,n,process.stderr,k)}],function(k){d(k)})}.bind(this)],function(d,e){m(d,e)})}};"undefined"!==typeof module&&module.exports&&(module.exports=p)})();
