var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,k,n){if(f==Array.prototype||f==Object.prototype)return f;f[k]=n.value;return f};
$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<f.length;++k){var n=f[k];if(n&&n.Math==Math)return n}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,k){var n=$jscomp.propertyToPolyfillSymbol[k];if(null==n)return f[k];n=f[n];return void 0!==n?n:f[k]};$jscomp.polyfill=function(f,k,n,t){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,k,n,t):$jscomp.polyfillUnisolated(f,k,n,t))};
$jscomp.polyfillUnisolated=function(f,k,n,t){n=$jscomp.global;f=f.split(".");for(t=0;t<f.length-1;t++){var u=f[t];if(!(u in n))return;n=n[u]}f=f[f.length-1];t=n[f];k=k(t);k!=t&&null!=k&&$jscomp.defineProperty(n,f,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(f,k,n,t){var u=f.split(".");f=1===u.length;t=u[0];t=!f&&t in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var y=0;y<u.length-1;y++){var C=u[y];if(!(C in t))return;t=t[C]}u=u[u.length-1];n=$jscomp.IS_SYMBOL_NATIVE&&"es6"===n?t[u]:null;k=k(n);null!=k&&(f?$jscomp.defineProperty($jscomp.polyfills,u,{configurable:!0,writable:!0,value:k}):k!==n&&(void 0===$jscomp.propertyToPolyfillSymbol[u]&&(n=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[u]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(u):$jscomp.POLYFILL_PREFIX+n+"$"+u),$jscomp.defineProperty(t,$jscomp.propertyToPolyfillSymbol[u],{configurable:!0,writable:!0,value:k})))};$jscomp.underscoreProtoCanBeSet=function(){var f={a:!0},k={};try{return k.__proto__=f,k.a}catch(n){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(f,k){f.__proto__=k;if(f.__proto__!==k)throw new TypeError(f+" is not extensible");return f}:null;$jscomp.arrayIteratorImpl=function(f){var k=0;return function(){return k<f.length?{done:!1,value:f[k++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};
$jscomp.makeIterator=function(f){var k="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return k?k.call(f):$jscomp.arrayIterator(f)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(f){if(!(f instanceof Object))throw new TypeError("Iterator result "+f+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(f){this.yieldResult=f};$jscomp.generator.Context.prototype.throw_=function(f){this.abruptCompletion_={exception:f,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(f){this.abruptCompletion_={return:f};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(f){this.abruptCompletion_={jumpTo:f};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(f,k){this.nextAddress=k;return{value:f}};$jscomp.generator.Context.prototype.yieldAll=function(f,k){f=$jscomp.makeIterator(f);var n=f.next();$jscomp.generator.ensureIteratorResultIsObject_(n);if(n.done)this.yieldResult=n.value,this.nextAddress=k;else return this.yieldAllIterator_=f,this.yield(n.value,k)};
$jscomp.generator.Context.prototype.jumpTo=function(f){this.nextAddress=f};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(f,k){this.catchAddress_=f;void 0!=k&&(this.finallyAddress_=k)};$jscomp.generator.Context.prototype.setFinallyBlock=function(f){this.catchAddress_=0;this.finallyAddress_=f||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(f,k){this.nextAddress=f;this.catchAddress_=k||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(f){this.catchAddress_=f||0;f=this.abruptCompletion_.exception;this.abruptCompletion_=null;return f};$jscomp.generator.Context.prototype.enterFinallyBlock=function(f,k,n){n?this.finallyContexts_[n]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=f||0;this.finallyAddress_=k||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(f,k){k=this.finallyContexts_.splice(k||0)[0];if(k=this.abruptCompletion_=this.abruptCompletion_||k){if(k.isException)return this.jumpToErrorHandler_();void 0!=k.jumpTo&&this.finallyAddress_<k.jumpTo?(this.nextAddress=k.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=f};$jscomp.generator.Context.prototype.forIn=function(f){return new $jscomp.generator.Context.PropertyIterator(f)};
$jscomp.generator.Context.PropertyIterator=function(f){this.object_=f;this.properties_=[];for(var k in f)this.properties_.push(k);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var f=this.properties_.pop();if(f in this.object_)return f}return null};$jscomp.generator.Engine_=function(f){this.context_=new $jscomp.generator.Context;this.program_=f};
$jscomp.generator.Engine_.prototype.next_=function(f){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,f,this.context_.next_);this.context_.next_(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(f){this.context_.start_();var k=this.context_.yieldAllIterator_;if(k)return this.yieldAllStep_("return"in k?k["return"]:function(n){return{value:n,done:!0}},f,this.context_.return);this.context_.return(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(f){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],f,this.context_.next_);this.context_.throw_(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(f,k,n){try{var t=f.call(this.context_.yieldAllIterator_,k);$jscomp.generator.ensureIteratorResultIsObject_(t);if(!t.done)return this.context_.stop_(),t;var u=t.value}catch(y){return this.context_.yieldAllIterator_=null,this.context_.throw_(y),this.nextStep_()}this.context_.yieldAllIterator_=null;n.call(this.context_,u);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var f=this.program_(this.context_);if(f)return this.context_.stop_(),{value:f.value,done:!1}}catch(k){this.context_.yieldResult=void 0,this.context_.throw_(k)}this.context_.stop_();if(this.context_.abruptCompletion_){f=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(f.isException)throw f.exception;return{value:f.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(f){this.next=function(k){return f.next_(k)};this.throw=function(k){return f.throw_(k)};this.return=function(k){return f.return_(k)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(f,k){k=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(k));$jscomp.setPrototypeOf&&f.prototype&&$jscomp.setPrototypeOf(k,f.prototype);return k};
$jscomp.asyncExecutePromiseGenerator=function(f){function k(t){return f.next(t)}function n(t){return f.throw(t)}return new Promise(function(t,u){function y(C){C.done?t(C.value):Promise.resolve(C.value).then(k,n).then(y,u)}y(f.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(f){return $jscomp.asyncExecutePromiseGenerator(f())};$jscomp.asyncExecutePromiseGeneratorProgram=function(f){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(f)))};
$jscomp.polyfill("Array.prototype.includes",function(f){return f?f:function(k,n){var t=this;t instanceof String&&(t=String(t));var u=t.length;n=n||0;for(0>n&&(n=Math.max(n+u,0));n<u;n++){var y=t[n];if(y===k||Object.is(y,k))return!0}return!1}},"es7","es3");
const ar=require("ar-async"),async=require("async"),chardet=require("chardet"),CombinedStream=require("combined-stream"),decompress=require("decompress"),decompressTargz=require("decompress-targz"),ElfParser=require("elfy").Parser,encoding=require("encoding"),fs=require("fs"),fstream=require("fstream"),log=require("npmlog"),mkdirp=require("mkdirp"),path=require("path"),rimraf=require("rimraf"),shelljs=require("shelljs"),stripbom=require("strip-bom"),temp=require("temp"),uglify=require("terser"),util=
require("util"),Validator=require("jsonschema").Validator,zlib=require("zlib"),crypto=require("crypto"),tarFilterPack=require("./tar-filter-pack"),errHndl=require("./base/error-handler"),hasProperty=require("./util/property");
(function(){function f(a){this.objectId=pa++;this.verbose=!1;this.silent=!0;a&&a.level&&(log.level=a.level,-1!==["warn","error"].indexOf(a.level)&&(this.silent=!1));this.noclean=!1;a&&!0===a.noclean&&(this.noclean=!0);this.minify=!0;a&&hasProperty(a,"minify")&&(this.minify=a.minify);this.excludeFiles=[];a&&hasProperty(a,"excludefiles")&&(a.excludefiles instanceof Array?this.excludeFiles=a.excludefiles:this.excludeFiles.push(a.excludefiles));this.rom=!1;a&&hasProperty(a,"rom")&&(this.rom=a.rom);this.encrypt=
!1;a&&hasProperty(a,"encrypt")&&(this.encrypt=a.encrypt);this.sign="";a&&hasProperty(a,"sign")&&(this.sign=a.sign);this.certificate="";a&&hasProperty(a,"certificate")&&(this.certificate=a.certificate);log.verbose("Xtor Packager id="+this.objectId);this.rscCount=this.appCount=0;this.services=[];this.resources=[];this.pkgServiceNames=[];this.pkgResourceNames=[];this.pkgVersion=a.pkgversion;a&&hasProperty(a,"pkgid")&&(this.pkgId=a.pkgid);a&&hasProperty(a,"pkginfofile")&&(this.pkginfofile=a.pkginfofile)}
function k(){this.srcDir="";this.dstDirs=[];this.valid=!1;this.dirName=this.serviceInfo=""}function n(a){log.verbose("loadPkgInfo");let b;if(this.pkginfofile)if(log.silly("Use pkginfofile option"),fs.existsSync(this.pkginfofile)){if("packageinfo.json"!==path.basename(this.pkginfofile))return setImmediate(a,errHndl.getErrMsg("INVALID_FILE","packageinfo.json"));b=H(this.pkginfofile,!0);try{log.verbose("PKGINFO: "+b);this.pkginfo=JSON.parse(b);if(!hasProperty(this.pkginfo,"id"))return setImmediate(a,
errHndl.getErrMsg("REQUIRED_FIELD","id"));this.pkgId=this.pkginfo.id;this.pkgVersion=this.pkgVersion||this.pkginfo.version;setImmediate(a)}catch(c){return setImmediate(a,errHndl.getErrMsg("INVALID_JSON_FORMAT","packageinfo.json"))}}else return setImmediate(a,errHndl.getErrMsg("NOT_EXIST_PATH",this.pkginfofile));else if(this.pkgDir){log.silly("Use packageinfo.json from PKG_DIR");b=H(path.join(this.pkgDir,"packageinfo.json"));try{log.verbose("PKGINFO: "+b);this.pkginfo=JSON.parse(b);if(!hasProperty(this.pkginfo,
"id"))return setImmediate(a,errHndl.getErrMsg("REQUIRED_FIELD","id"));this.pkgId=this.pkginfo.id;this.pkgVersion=this.pkgVersion||this.pkginfo.version;setImmediate(a)}catch(c){return setImmediate(a,errHndl.getErrMsg("INVALID_JSON_FORMAT","packageinfo.json"))}}else return setImmediate(a)}function t(a){log.verbose("loadAppInfo");if(0===this.appCount)return setImmediate(a);var b=path.join(this.appDir,"appinfo.json");b=H(b,!0);try{this.appinfo=JSON.parse(b),log.verbose("APPINFO: "+b),this.pkgVersion=
this.pkgVersion||this.appinfo.version||"1.0.0",setImmediate(a)}catch(c){setImmediate(a,c)}}function u(a){log.verbose("checkAppInfo");if(0===this.appCount)return setImmediate(a);if(this.pkgJSExist&&this.appinfo.main&&this.appinfo.main.match(/(\.html|\.htm)$/gi)){var b=path.join(this.appDir,this.appinfo.main);if(!fs.existsSync(b))return setImmediate(a,errHndl.getErrMsg("NOT_EXIST_PATH",this.appinfo.main));const c=RegExp("(<script[^>]*src[ \t]*=[ \t]*['\"])[^'\"]*/enyo.js(['\"])");if(fs.readFileSync(b).toString().match(c))return setImmediate(a,
errHndl.getErrMsg("NOT_SUPPORT_ENYO"))}if(!this.appinfo.id||void 0===this.appinfo.id)return setImmediate(a,errHndl.getErrMsg("REQUIRED_FIELD","id"));if(1>this.appinfo.id.length||!/^[a-z0-9.+-]*$/.test(this.appinfo.id))return log.error(errHndl.getErrMsg("INVALID_VALUE","id",this.appinfo.id)),setImmediate(a,errHndl.getErrMsg("INVALID_ID_RULE"));if(this.pkgId&&0!==this.appinfo.id.indexOf(this.pkgId))return setImmediate(a,errHndl.getErrMsg("INVALID_APPID",this.pkgId));if(!this.appinfo.version||void 0===
this.appinfo.version)return setImmediate(a,errHndl.getErrMsg("REQUIRED_FIELD","version"));if(1>this.appinfo.version.length||!/^([1-9]\d{0,8}|\d)\.([1-9]\d{0,8}|\d)\.([1-9]\d{0,8}|\d)$/.test(this.appinfo.version))return log.error(errHndl.getErrMsg("INVALID_VALUE","version",this.appinfo.version)),setImmediate(a,errHndl.getErrMsg("INVALID_VERSION_RULE"));if(this.appinfo.type&&this.appinfo.type.match(/clock/gi))return setImmediate(a);b=path.resolve(__dirname,"../files/schema/ApplicationDescription.schema");
async.waterfall([fs.readFile.bind(this,b,"utf-8"),function(c,e){try{const d=JSON.parse(c),g=d.required;if(g)for(const h in d.properties)-1!==g.indexOf(h)&&(d.properties[h].required=!0);e(null,d)}catch(d){e(errHndl.getErrMsg("INVALID_JSON_FORMAT","AppDescription schema"))}},function(c,e){try{e(null,(new Validator).validate(this.appinfo,c))}catch(d){log.error(d),e(errHndl.getErrMsg("INVALID_JSON_FORMAT"))}}.bind(this)],function(c,e){if(c)setImmediate(a,c);else{if(e&&0<e.errors.length){c="";for(const d in e.errors){let g=
e.errors[d].property+" "+e.errors[d].message;-1<g.indexOf("instance.")&&(g=g.substring(9),c=c.concat("\n"),c=c.concat(g))}c=errHndl.getErrMsg("INVALID_FILE","appinfo.json",c);return setImmediate(a,c)}log.verbose("APPINFO is valid");setImmediate(a)}})}function y(a){log.verbose("fillAssetsField");if(0===this.appCount)return setImmediate(a);this.appinfo.assets=this.appinfo.assets||[];for(var b in this.appinfo)hasProperty(this.appinfo,b)&&ca[b]&&-1===this.appinfo.assets.indexOf(this.appinfo[b])&&this.appinfo[b]&&
this.appinfo.assets.push(this.appinfo[b]);const c=this.originAppDir;b=path.join(this.originAppDir,"resources");const e=[],d=[];try{if(!fs.lstatSync(b).isDirectory())return setImmediate(a,null)}catch(g){if("ENOENT"===g.code)return setImmediate(a,null)}async.series([M.bind(null,b,"appinfo.json",e,1),function(g){async.forEach(e,function(h,l){H(h,!0,function(m,q){try{const p=JSON.parse(q),v=path.dirname(h);for(const r in p)if(hasProperty(p,r)&&ca[r]&&p[r]){const x=path.join(v,p[r]),w=path.relative(c,
x);-1===d.indexOf(w)&&d.push(w)}setImmediate(l,null)}catch(p){log.error(p),setImmediate(l,errHndl.getErrMsg("INVALID_JSON_FORMAT",h))}})},function(h){setImmediate(g,h)})},function(g){this.appinfo.assets=this.appinfo.assets.concat(d);setImmediate(g,null)}.bind(this)],function(g){setImmediate(a,g)})}function C(a){log.verbose("createTmpDir");this.tempDir=temp.path({prefix:"com.palm.ares.hermes.bdOpenwebOS"})+".d";log.verbose("temp dir = "+this.tempDir);mkdirp(this.tempDir,a)}function qa(a){log.verbose("createAppDir");
if(0===this.appCount)return setImmediate(a);try{this.applicationDir=path.resolve(this.tempDir,"data/usr/palm","applications",this.appinfo.id),log.verbose("application dir = "+this.applicationDir),mkdirp(this.applicationDir,a)}catch(b){return setImmediate(a,b)}}function E(a,b,c){function e(m,q,p,v,r,x){I[q]&&m.push({type:q,basePath:p,relPath:v,isSubPath:r,indRelPath:x})}function d(m,q,p,v){async.waterfall([fs.readdir.bind(null,m),function(r,x){if(0===r.length)return e(p,"dir",q,path.relative(q,m),
!0,null),setImmediate(x);async.forEachSeries(r,function(w,z){const A=path.join(m,w),B=path.relative(q,A);async.waterfall([fs.lstat.bind(null,A),function(D,F){if(D.isSymbolicLink()){try{var G=fs.realpathSync(A)}catch(J){return"ENOENT"===J.code?(log.warn("The file for symbolic link ("+A+") is missing..."),setImmediate(F)):setImmediate(F,J)}D=fs.readlinkSync(A);if(-1!==G.indexOf(q))e(p,"symlink",q,B,!0,D);else{G=fs.statSync(A);if(G.isDirectory())return d(A,q,p,F);G.isFile()&&e(p,"file",q,B,!0,null)}}else{if(D.isDirectory())return d(A,
q,p,F);D.isFile()&&e(p,"file",q,B,!0,null)}setImmediate(F)}],z)},x)}],function(r){return setImmediate(v,r)})}log.verbose("copySrcToDst");const g=[],h=this,l=!(!h.minify||h.minifyDone);a=path.normalize(path.resolve(a));b=path.normalize(path.resolve(b));async.series([function(m){fs.statSync(a).isFile()?(e(g,"file",path.dirname(a),path.basename(a),!0,null),setImmediate(m)):d(a,a,g,m)},function(m,q,p,v){try{async.forEachSeries(m,function(r,x){if(I[r.type]){if(!r.relPath)return log.verbose("copySrcToDst#_copySrcToDst#ignore 'unknown path'"),
setImmediate(x);if(r.type===I.dir)return mkdirp.sync(path.join(q,r.relPath)),setImmediate(x);var w=path.dirname(path.join(q,r.relPath));fs.existsSync(w)||mkdirp.sync(w);if(r.type===I.symlink){if(r.isSubPath&&r.indRelPath){var z=path.join(q,r.relPath);fs.existsSync(z)&&fs.lstatSync(z).isSymbolicLink()&&fs.unlinkSync(z);fs.symlinkSync(r.indRelPath,z,null)}}else if(w=path.join(r.basePath,r.relPath),fs.existsSync(w))if(p&&".js"===path.extname(w)&&-1===r.relPath.indexOf("node_modules")){log.verbose("copySrcToDst#_copySrcToDst(),require minification # sourceFile:",
w);try{z=uglify.minify(fs.readFileSync(w,"utf8"));if(z.error)throw z.error;fs.writeFileSync(path.join(q,r.relPath),z.code,"utf8")}catch(A){return log.verbose(util.format("failed to uglify code %s: %s",w,A.stack)),setImmediate(x,errHndl.getErrMsg("FAILED_MINIFY",w))}}else shelljs.cp("-Rf",w,path.join(q,r.relPath,".."));else log.verbose("copySrcToDst#_copySrcToDst#ignore '"+r.relPath+"'");setImmediate(x)}else log.verbose("copySrcToDst#_copySrcToDst#ignore 'unknown file type'("+r.type+")")},function(r){!r&&
p&&(h.minifyDone=!0);setImmediate(v,r)})}catch(r){setImmediate(v,r)}}.bind(null,g,b,l)],function(m){c(m)})}function ra(a){log.verbose("checkELFHeader");const b=this,c=Buffer.alloc(64),e=path.resolve(path.join(this.appDir,this.appinfo.main));if(!fs.existsSync(e))return setImmediate(a,errHndl.getErrMsg("NOT_EXIST_PATH",e));const d=fs.openSync(e,"r"),g=fs.fstatSync(d),h=new ElfParser;if(64>g.size)return log.verbose("checkELFHeader():","file size is smaller than ELF Header size"),setImmediate(a);fs.read(d,
c,0,64,0,function(l,m,q){if(64>m||l)return log.verbose("checkELFHeader():","err:",l,", bytesRead:",m),log.verbose("checkELFHeader():","readBuf to parse ELF header is small or error occurred during reading file."),setImmediate(a);l="\u007fELF"!==q.slice(0,4).toString()?!1:!0;if(l){log.verbose("checkELFHeader():",e+" is ELF format");try{const p=h.parseHeader(q);log.verbose("checkELFHeader():","elfHeader:",p);p.machine&&p.machine.match(/86$/)?b.architecture="i586":p.machine&&p.machine.match(/amd64$/)?
b.architecture="x86_64":p.machine&&p.machine.match(/AArch64$/)?b.architecture="aarch64":b.architecture=p.machine}catch(p){log.verbose("checkELFHeader():","exception:",p)}}else log.verbose("checkELFHeader():",e+" is not ELF format");log.verbose("checkELFHeader():","machine:",b.architecture);fs.close(d);setImmediate(a)})}function sa(a){log.verbose("copyApp");if(0===this.appCount)return setImmediate(a);this.dataCopyCount++;log.verbose("copyApp():","copy "+this.appDir+" ==> "+this.applicationDir);E.call(this,
this.appDir,this.applicationDir,a)}function ta(a){function b(d,g){log.verbose("copyAssets():_handleAssets(): ",d);path.resolve(this.originAppDir)===path.resolve(this.appDir)?c.call(this,d,g):async.series([c.bind(this,d),e.bind(this,d)],g)}function c(d,g){log.verbose("copyAssets():","_checkAppinfo()");let h;if(path.resolve(d)===path.normalize(d))return g(errHndl.getErrMsg("NOT_RELATIVE_PATH_APPINFO",d));h=path.join(this.originAppDir,d);if(0!==path.resolve(h).indexOf(this.originAppDir))return g(errHndl.getErrMsg("NOT_RELATIVE_PATH_APPINFO",
d));if(!fs.existsSync(h)&&!this.rom)return d=errHndl.getErrMsg("NOT_EXIST_PATH",d),0===path.basename(h).indexOf("$")?setImmediate(g):setImmediate(g,d);setImmediate(g)}function e(d,g){log.verbose("copyAssets():","_copyAssets()");log.verbose("copyAssets # '"+d+"' will be located in app directory");const h=path.join(this.originAppDir,d),l=this.appDir;async.series([function(m){fs.existsSync(l)?setImmediate(m):mkdirp(l,m)}],function(m){if(m)return setImmediate(g,m);shelljs.cp("-Rf",h,l);setImmediate(g)})}
log.verbose("copyAssets");if(0===this.appCount)return setImmediate(a);try{async.forEachSeries(this.appinfo.assets,b.bind(this),a)}catch(d){return setImmediate(a,d)}}function N(a){log.verbose("excludeIpkFileFromApp");this.excludeFiles=this.excludeFiles.concat(["[.]*[\\.]ipk",".DS_Store",".vscode",".reloadignore",".launchparams.json"]);setImmediate(a)}function da(a,b,c,e,d){async.waterfall([fs.readdir.bind(null,c),function(g,h){async.forEach(g,function(l,m){const q=path.join(c,l);async.waterfall([fs.lstat.bind(null,
q),function(p,v){let r=!1;1<e&&b.test(l)&&(r=!0,a.push(q));!r&&p.isDirectory()?da(a,b,q,e+1,v):setImmediate(v)}],m)},h)}],function(g){setImmediate(d,g)})}function O(a){log.verbose("excludeFromApp");var b=(0===this.appCount?this.excludeFiles:this.excludeFiles.concat(this.appinfo.exclude||[])).map(function(d){return d.replace(/^\./g,"^\\.").replace(/^\*/g,"").replace(/$/g,"$")},this).join("|");b=new RegExp(b,"i");log.silly("excludeFromApp():regExp=",b);const c=[],e=path.resolve(this.tempDir,"data/usr/palm");
async.series([da.bind(this,c,b,e,0),function(d){try{const g=["appinfo.json","services.json","packageinfo.json","resourceinfo.json"],h=[],l=[];c.forEach(function(m){if(g.includes(path.basename(m)))h.push(path.basename(m));else{const q=m.slice(e.length+1);l.push(q.slice(q.indexOf(path.sep)+1));shelljs.rm("-rf",m)}});0<h.length&&console.log("Cannot exclude:",h);0<l.length&&console.log("Excluded:",l);setImmediate(d)}catch(g){setImmediate(d,g)}}],function(d){if(d)return setImmediate(a,d);setImmediate(a)})}
function P(a){log.verbose("createPackageDir");this.rom?setImmediate(a):(this.packageDir=path.join(this.tempDir,"data/usr/palm","packages",this.pkgId||this.appinfo.id),mkdirp(this.packageDir,a))}function Q(a){function b(e,d,g){if(!/^[a-z0-9.+-]*$/.test(e))return log.error(errHndl.getErrMsg("INVALID_VALUE","pkg id",e)),setImmediate(g,errHndl.getErrMsg("INVALID_ID_RULE"));if(!/^([1-9]\d{0,8}|\d)\.([1-9]\d{0,8}|\d)\.([1-9]\d{0,8}|\d)$/.test(d))return log.error(errHndl.getErrMsg("INVALID_VALUE","pkg version",
d)),setImmediate(g,errHndl.getErrMsg("INVALID_VERSION_RULE"))}log.verbose("fillPackageDir");if(this.rom)setImmediate(a);else{var c="";this.pkginfo?(this.pkginfo.version||(this.pkginfo.version=this.pkgVersion||"1.0.0"),b(this.pkginfo.id,this.pkginfo.version,a),c=JSON.stringify(this.pkginfo,null,2)+"\n"):(c={id:this.pkgId||this.appinfo.id,version:this.pkgVersion||"1.0.0"},this.appinfo&&(c.app=this.appinfo.id),b(c.id,c.version,a),c=JSON.stringify(c,null,2)+"\n");log.verbose("Generating packageinfo.json: "+
c);fs.writeFile(path.join(this.packageDir,"packageinfo.json"),c,a)}}function R(a,b){log.verbose("loadPackageProperties");const c=this;c.packageProperties={};async.forEach(a,function(e,d){function g(h){h=h.replace(/\\/g,"/").trim();const l=h.lastIndexOf("/");h=-1!==l?h.slice(l+1):h;c.packageProperties[h]=this.fileMode}e=path.join(e,"package.properties");if(fs.existsSync(e)){e=fs.readFileSync(e);try{log.verbose("PACKAGE PROPERTIES: "+e);const h=e.toString().split("\n");let l;for(const m in h)if(0===
h[m].indexOf("filemode.")){l=h[m].indexOf("=");const q=h[m].slice(l+1).trim().split(",");this.fileMode=h[m].slice(9,l).trim();q.forEach(g)}setImmediate(d)}catch(h){setImmediate(d,h)}}else setImmediate(d)},function(e){c.excludeFiles=c.excludeFiles.concat(["package.properties"]);setImmediate(b,e)})}function S(a,b){log.verbose("outputPackage");if(this.rom)E.call(this,path.join(this.tempDir,"data"),a,b);else{const c=this.tempDir,e=path.join(c,"ctrl"),d=path.join(c,"control.tar.gz"),g=path.join(c,"data"),
h=path.join(c,"data.tar.gz");async.series([ua.bind(this,this.pkgId,this.pkgVersion),va.bind(this,g),K.bind(this,g,h),L.bind(this,e),ea.bind(this,e,!1),wa.bind(this,e,h),K.bind(this,e,d),fa.bind(this,c),xa.bind(this),ya.bind(this,a),ha.bind(this,c)],function(l){l?setImmediate(b,l):setImmediate(b)})}}function ua(a,b,c){log.verbose("decidePkgName");this.pkg=0!==this.appCount?{name:a||this.appinfo.id,version:b||this.appinfo.version}:0<this.services.length?{name:a||this.services[0].serviceInfo.id||this.services[0].serviceInfo.services[0].name,
version:b||"1.0.0"}:{name:a||"unknown",version:b||"1.0.0"};log.silly("decidePkgName:",this.pkg);setImmediate(c)}function va(a,b){function c(d,g){fs.lstat(d,function(h,l){let m=l.size;!h&&l.isDirectory()?fs.readdir(d,function(q,p){if(q)return g(q);async.forEach(p,function(v,r){c(path.join(d,v),function(x,w){m+=w;r(x)})},function(v){g(v,m)})}):g(h,m)})}log.verbose("getFileSize");const e=this;async.waterfall([c.bind(this,a)],function(d,g){!d&&g&&(log.verbose("getFileSize#Installed-Size:",g),e.size=g);
setImmediate(b,d)})}function L(a,b){log.verbose("createDir = "+a);mkdirp(a,b)}function ea(a,b,c){a=path.join(a,"control");log.verbose("createControlFile : "+a);const e=["Package: "+this.pkg.name,"Version: "+this.pkg.version,"Section: misc","Priority: optional","Architecture: "+(this.architecture||"all"),"Installed-Size: "+(this.size||1234),"Maintainer: N/A <nobody@example.com>","Description: This is a webOS application.","webOS-Package-Format-Version: 2","webOS-Packager-Version: x.y.x"];b&&e.push("Encrypt-Algorithm: AES-256-CBC");
e.push("");fs.writeFile(a,e.join("\n"),c)}function wa(a,b,c){log.verbose("createSign");if(!this.sign||!this.certificate)return log.verbose("App signing skipped"),setImmediate(c);const e=path.join(a,"data.tar.gz.sha256.txt"),d=path.resolve(this.sign),g=path.resolve(this.certificate);log.verbose("dataTgzPath : "+b+", sigfile : "+e);log.verbose("keyPath : "+d+", crtPath : "+g);try{shelljs.cp("-f",g,a);const h=fs.readFileSync(d,"utf-8"),l=fs.readFileSync(b),m=crypto.createSign("sha256");m.update(l);m.end();
const q=m.sign(h),p=Buffer.from(q).toString("base64");fs.writeFile(e,p,c)}catch(h){setImmediate(c,h)}}function fa(a,b){a=path.join(a,"debian-binary");log.verbose("createDebianBinary : "+a);fs.writeFile(a,"2.0\n",b)}function K(a,b,c){log.verbose("makeTgz "+b+" from "+a);const e=this.pkgServiceNames;fstream.Reader({path:a,type:"Directory",filter:function(d){if("Directory"===d.props.type){let g=201;-1!==e.indexOf(d.props.basename)&&(g=219);d.props.mode|=d.props.mode>>>2&g}else"File"===d.props.type&&
(d.props.mode|=4);return!0}}).pipe(tarFilterPack({noProprietary:!0,fromBase:!0,permission:this.packageProperties})).pipe(zlib.createGzip()).pipe(fstream.Writer(b)).on("close",c).on("error",d=>{log.error(d);c(d)})}function xa(a){log.verbose("setIpkFileName");let b=this.pkg.name;this.ipkFileName=b=this.pkg.version?b.concat("_"+this.pkg.version+"_"+("i586"===this.architecture?"x86":this.architecture||"all")+".ipk"):b.concat(".ipk");setImmediate(a)}function ya(a,b){log.verbose("removeExistingIpk");if(0===
this.appCount)return setImmediate(b);const c=path.join(a,this.ipkFileName);fs.exists(c,function(e){e?fs.unlink(c,b):setImmediate(b)})}function T(a,b){return String(a+"                                     ").slice(0,b)}function ia(a,b){const c=Math.floor(Date.now()/1E3);return T(a,16)+T(c,12)+"0     0     100644  "+T(b,10)+"`\n"}function ha(a,b){this.IpkDir=a;this.ipk=path.join(a,this.ipkFileName);log.verbose("makeIpk in dir "+this.IpkDir+" file "+this.ipkFileName);a=ia("debian-binary",4)+"2.0\n";
const c=this,e=CombinedStream.create(),d=fstream.Writer(this.ipk);e.append("!<arch>\n"+a);["control.tar.gz","data.tar.gz"].forEach(function(g){var h=path.join(c.IpkDir,g);const l=fstream.Reader({path:h,type:"File"});h=fs.statSync(h);e.append(ia(g,h.size));e.append(l);0!==h.size%2&&(log.verbose("Adding a filler for file "+g),e.append("\n"))},this);e.pipe(d);d.on("close",function(){setImmediate(b)});d.on("error",b)}function U(a){log.verbose("cleanupTmpDir");this.noclean?(console.log("Skipping removal of  "+
this.tempDir),setImmediate(a)):rimraf(this.tempDir,function(b){log.verbose("cleanup(): removed "+this.tempDir);setImmediate(a,b)}.bind(this))}function za(a,b,c){log.verbose("checkDirectory: "+b);if(fs.existsSync(b))if(fs.statSync(b).isDirectory()){b=fs.realpathSync(b);if(a.force)return c();if(fs.existsSync(path.join(b,"appinfo.json")))this.appCount++,log.verbose("FOUND appinfo.json, appCount "+this.appCount),1<this.appCount?c(errHndl.getErrMsg("OVER_APPCOUNT")):0<this.rscCount?c(errHndl.getErrMsg("NOT_WITH_RESOURCE")):
(this.originAppDir=this.appDir=b,fs.existsSync(path.join(b,"package.js"))&&(this.pkgJSExist=!0),c());else if(fs.existsSync(path.join(b,"packageinfo.json")))this.pkgDir=b,c();else if(fs.existsSync(path.join(b,"services.json")))0<this.rscCount&&c(errHndl.getErrMsg("NOT_WITH_RESOURCE")),this.svcDir=this.svcDir||[],this.svcDir=this.svcDir.concat(b),c();else if(fs.existsSync(path.join(b,"resourceinfo.json")))this.rscCount++,log.verbose("FOUND resourceinfo.json, rscCount "+this.rscCount),(0<this.appCount||
this.svcDir&&0<this.svcDir.length)&&c(errHndl.getErrMsg("NOT_WITH_RESOURCE")),this.resources=this.resources||[],a={},a.dir=b,this.resources=this.resources.concat(a),c();else if(fs.existsSync(path.join(b,"account-templates.json")))c(errHndl.getErrMsg("NO_ACCOUNT"));else{const e=[];this.svcDir=this.svcDir||[];this.svcDir=this.svcDir.concat(b);V.call(this,e,function(){0<e.length?(0<this.rscCount&&c(errHndl.getErrMsg("NOT_WITH_RESOURCE")),c()):c(errHndl.getErrMsg("NO_METAFILE","APP_DIR/SVC_DIR",b))})}}else c(errHndl.getErrMsg("NOT_DIRTYPE_PATH",
b));else c(errHndl.getErrMsg("NOT_EXIST_PATH",b))}function V(a,b){log.verbose("findServiceDir");const c=[].concat(this.svcDir||this.originAppDir||[]),e=[];if(0===c.length)return setImmediate(b);async.forEach(c,function(d,g){M(d,"services.json",e,3,function(h){if(h)return setImmediate(g,h);e.forEach(function(l){const m=new k;m.srcDir=path.dirname(l);m.dirName=path.basename(m.srcDir);a.push(m)});e.pop();setImmediate(g,h)})},function(d){setImmediate(b,d)})}function M(a,b,c,e,d){if(0>=e)return d();async.waterfall([fs.readdir.bind(null,
a),function(g,h){async.forEach(g,function(l,m){const q=path.join(a,l);async.waterfall([fs.lstat.bind(null,q),function(p,v){p.isFile()?(l===b&&c.push(q),v()):p.isDirectory()?M(q,b,c,e-1,v):v()}],m)},h)}],function(g){d(g)})}function ja(a){log.verbose("loadServiceInfo");for(const b in this.services){const c=path.join(this.services[b].srcDir,"services.json");try{const e=fs.readFileSync(c),d=JSON.parse(e);hasProperty(d,"id")&&hasProperty(d,"services")&&(this.services[b].serviceInfo=d,this.services[b].valid=
!0)}catch(e){return setImmediate(a,e)}}log.verbose("num of serviceInfo: "+this.services.length);setImmediate(a)}function ka(a){log.verbose("checkServiceInfo");const b=this.pkgId||this.appinfo.id,c=[];let e=!1;this.services.forEach(function(d){!1!==d.valid&&c.push(W(d.serviceInfo)[0])});c.forEach(function(d){0!==d.indexOf(b+".")&&(e=!0)});if(e)return setImmediate(a,errHndl.getErrMsg("INVALID_SERVICEID",b));setImmediate(a)}function la(a){log.verbose("createServiceDir");this.services.forEach(function(b){!1!==
b.valid&&W(b.serviceInfo).forEach(function(c){c=path.join(this.tempDir,"data/usr/palm","services",c);b.dstDirs.push(c);try{mkdirp.sync(c)}catch(e){return setImmediate(a,e)}}.bind(this))}.bind(this));setImmediate(a)}function ma(a){log.verbose("copyService");const b=this,c=this.services.filter(function(e){return e.valid});try{async.forEachSeries(c,function(e,d){async.forEach(e.dstDirs,function(g,h){b.dataCopyCount++;E.call(b,e.srcDir,g,h)},d)},a)}catch(e){setImmediate(a,e)}}function na(a){log.verbose("addServiceInPkgInfo");
if(this.rom)setImmediate(a);else{var b=path.join(this.packageDir,"packageinfo.json");let c,e;try{const d=fs.readFileSync(b);e=0;log.verbose("PACKAGEINFO: "+d);c=JSON.parse(d)}catch(d){console.error(d),setImmediate(a,d)}this.services.filter(function(d){return d.valid}).forEach(function(d){W(d.serviceInfo).forEach(function(g){this.pkgServiceNames.push(g);e++}.bind(this))}.bind(this));0<e?(c.services=this.pkgServiceNames,b=JSON.stringify(c,null,2)+"\n",log.verbose("Modified package.json: "+b),fs.writeFile(path.join(this.packageDir,
"packageinfo.json"),b,a)):setImmediate(a)}}function Aa(a){function b(g){if(this.dirName===g)try{const h=path.join(this.applicationDir,this.dirName);shelljs.rm("-rf",h)}catch(h){console.log("ERROR:"+h)}}log.verbose("removeServiceFromAppDir");if(0===this.appCount)return setImmediate(a);let c=this.applicationDir,e=!1;const d=fs.readdirSync(c);-1!==d.indexOf("services")&&(c=path.join(this.applicationDir,"services"),fs.statSync(c).isDirectory()&&(e=!0));if(!0===e)try{shelljs.rm("-rf",c)}catch(g){console.log("ERROR:"+
g)}else for(const g in this.services)this.dirName=this.services[g].dirName,d.forEach(b,this);setImmediate(a)}function Ba(a){log.verbose("loadResourceInfo");if(0===this.rscCount)return setImmediate(a);this.resources.forEach(function(b){const c=path.join(b.dir,"resourceinfo.json");try{const e=fs.readFileSync(c),d=JSON.parse(e);b.info=d}catch(e){return setImmediate(a,errHndl.getErrMsg("INVALID_JSON_FORMAT","resourceinfo.json"))}});log.verbose("num of resourceInfo: "+this.resources.length);setImmediate(a)}
function Ca(a){log.verbose("checkResourceInfo");const b=this.pkgId;this.resources.forEach(function(c){if(c.info.id){if(0!==c.info.id.indexOf(b))return setImmediate(a,errHndl.getErrMsg("INVALID_RESOURCEID",b));if(1>c.info.id.length||!/^[a-z0-9.+-]*$/.test(c.info.id))return log.error(errHndl.getErrMsg("INVALID_VALUE","id",c.info.id)),setImmediate(a,errHndl.getErrMsg("INVALID_ID_RULE"))}else return setImmediate(a,errHndl.getErrMsg("REQUIRED_FIELD","id"))});setImmediate(a)}function Da(a){log.verbose("createResourceDir");
this.resources.forEach(function(b){try{const c=path.join(this.tempDir,"data/usr/palm","resources",b.info.id);log.verbose("resource dir = "+c);b.dstDir=c;mkdirp.sync(c)}catch(c){return setImmediate(a,c)}}.bind(this));log.silly("this.resources:",this.resources);setImmediate(a)}function Ea(a){log.verbose("copyResource()");if(0===this.rscCount)return setImmediate(a);const b=this;try{async.forEachSeries(this.resources,function(c,e){b.dataCopyCount++;log.verbose("copyResource(), copy "+c.dir+" ==> "+c.dstDir);
E.call(b,c.dir,c.dstDir,e)},a)}catch(c){setImmediate(a,c)}}function Fa(a){log.verbose("addResourceInPkgInfo");if(!this.rom&&0<this.rscCount){const b=path.join(this.packageDir,"packageinfo.json");let c,e;try{e=fs.readFileSync(b),log.verbose("PACKAGEINFO: "+e),c=JSON.parse(e)}catch(d){console.error(d),setImmediate(a,d)}this.resources.forEach(function(d){this.pkgResourceNames.push(d.info.id)}.bind(this));c.resources=this.pkgResourceNames;e=JSON.stringify(c,null,2)+"\n";log.verbose("Modified package.json: "+
e);fs.writeFile(path.join(this.packageDir,"packageinfo.json"),e,a)}else setImmediate(a)}function X(a,b,c){log.verbose("copyData ** Only run when force packaging");if(b&&0===this.dataCopyCount){const e=path.join(this.tempDir,"data");async.forEachSeries(a,function(d,g){E.call(this,d,e,g)},function(d){setImmediate(c,d)})}else return setImmediate(c)}function W(a){log.verbose("getPkgServiceNames");return[a.id]}function Y(a,b){this.oldmask=process.umask(a);setImmediate(b)}function Z(a){this.oldmask&&process.umask(this.oldmask);
setImmediate(a)}function H(a,b,c){let e=fs.readFileSync(a);const d=chardet.detect(Buffer.from(e));-1===["UTF-8","ISO-8895-1"].indexOf(d)&&(log.verbose("Current Encoding Type>> "+d+"<<"),e=encoding.convert(e,"UTF-8",d));e=stripbom(e);b&&fs.writeFileSync(a,e,{encoding:"utf8"});"undefined"!==c&&"function"===typeof c&&setImmediate(c,null,e);return e}function aa(a){if(this.rom||!this.encrypt)setImmediate(a);else{log.verbose("encryptPackage");const b=this.encryptDir=path.join(this.tempDir,"encrypt"),c=
path.join(b,"ctrl"),e=path.join(b,"control.tar.gz"),d=path.join(b,"data"),g=path.join(b,"data.tar.gz");async.series([L.bind(this,b),L.bind(this,c),L.bind(this,d),Ga.bind(this,c),Ha.bind(this,d),K.bind(this,d,g),ea.bind(this,c,!0),K.bind(this,c,e),fa.bind(this,b),ha.bind(this,b)],function(h){h?setImmediate(a,h):(log.verbose("Success to encrypt pacakge"),setImmediate(a))})}}function Ga(a,b){log.verbose("generate symmmtic key & createkeyIVfile");this.key=Buffer.from(crypto.randomBytes(32),"base64");
this.iv=Buffer.from(crypto.randomBytes(16),"base64");try{const c=path.join(__dirname,"../","files","conf","pubkey.pem"),e=fs.readFileSync(c,"utf8"),d=crypto.publicEncrypt({key:e,padding:4},Buffer.from(this.key.toString("base64"))),g=crypto.publicEncrypt({key:e,padding:4},Buffer.from(this.iv.toString("base64"))),h=path.join(a,"key");fs.writeFileSync(h,d,"binary");const l=path.join(a,"iv");fs.writeFileSync(l,g,"binary")}catch(c){setImmediate(b,errHndl.getErrMsg(c))}setImmediate(b)}function ba(a,b){log.verbose("copyOutputToDst():",
"ipkFileName:",this.ipkFileName);if(this.rom)console.log("Create output directory to "+a),E.call(this,path.join(this.tempDir,"data"),a,b);else if(this.encrypt)console.log("Create encrypted "+this.ipkFileName+" to "+a),E.call(this,path.join(this.encryptDir,this.ipkFileName),a,b);else{let c="Create ";this.sign&&this.certificate&&(c=c.concat("signed "));console.log(c+this.ipkFileName+" to "+a);E.call(this,path.join(this.tempDir,this.ipkFileName),a,b)}}function Ha(a,b){log.verbose("encrypt plain ipk to /encrypt/data");
const c=path.join(this.tempDir,this.ipkFileName),e=path.join(a,this.ipkFileName);try{const d=fs.createReadStream(c),g=fs.createWriteStream(e),h=crypto.createCipheriv("aes-256-cbc",this.key,this.iv);g.on("close",function(){log.verbose("encrypted Ipk to "+e);setImmediate(b)}).on("error",function(l){setImmediate(b,l)});d.pipe(h).pipe(g)}catch(d){setImmediate(b,d)}}log.heading="packager";log.level="warn";const ca={main:!0,icon:!0,largeIcon:!0,bgImage:!0,splashBackground:!0,imageForRecents:!0,sysAssetsBasePath:!0},
I={file:"file",dir:"dir",symlink:"symlink"},oa={};"undefined"!==typeof module&&module.exports&&(module.exports=oa);let pa=0;oa.Packager=f;f.prototype={checkInputDirectories:function(a,b,c){log.verbose("checkInputDirectories: "+a);async.forEachSeries(a,za.bind(this,b),function(e){e?setImmediate(c,e):setImmediate(c)});return{app:this.appCount,resource:this.rscCount}},servicePackaging:function(a,b,c,e){log.verbose("callled servicePackaging");async.series([this.checkInputDirectories.bind(this,a,c),Y.bind(this,
0),n.bind(this),C.bind(this),N.bind(this),P.bind(this),Q.bind(this),V.bind(this,this.services),ja.bind(this),ka.bind(this),la.bind(this),ma.bind(this),na.bind(this),X.bind(this,a,c.force),R.bind(this,a),O.bind(this),S.bind(this,b),aa.bind(this),ba.bind(this,b),Z.bind(this),U.bind(this)],function(d){d?setImmediate(e,d):setImmediate(e,null,{ipk:this.ipk,msg:"Success"})}.bind(this))},resourcePackaging:function(a,b,c,e){log.verbose("callled resourcePackaging");this.dataCopyCount=0;async.series([this.checkInputDirectories.bind(this,
a,c),Y.bind(this,0),n.bind(this),C.bind(this),N.bind(this),P.bind(this),Q.bind(this),Ba.bind(this),Ca.bind(this),Da.bind(this),Ea.bind(this),Fa.bind(this),X.bind(this,a,c.force),R.bind(this,a),O.bind(this),S.bind(this,b),aa.bind(this),ba.bind(this,b),Z.bind(this),U.bind(this)],function(d){d?setImmediate(e,d):setImmediate(e,null,{ipk:this.ipk,msg:"Success"})}.bind(this))},generatePackage:function(a,b,c,e){log.verbose("generatePackage: from "+a);this.dataCopyCount=0;this.minifyDone=!this.minify;async.series([this.checkInputDirectories.bind(this,
a,c),Y.bind(this,0),n.bind(this),t.bind(this),u.bind(this),C.bind(this),qa.bind(this),ra.bind(this),y.bind(this),ta.bind(this),sa.bind(this),N.bind(this),P.bind(this),Q.bind(this),V.bind(this,this.services),ja.bind(this),ka.bind(this),la.bind(this),ma.bind(this),na.bind(this),Aa.bind(this),X.bind(this,a,c.force),R.bind(this,a),O.bind(this),S.bind(this,b),aa.bind(this),ba.bind(this,b),Z.bind(this),U.bind(this)],function(d){d?setImmediate(e,d):setImmediate(e,null,{ipk:this.ipk,msg:"Success"})}.bind(this))},
analyzeIPK:function(a,b){log.info("package#Packager#analyzeIPK()");let c,e,d,g;async.series([function(h){log.info("package#analyzeIPK()#_setConfig()");if("true"===a.info)return h(errHndl.getErrMsg("EMPTY_VALUE","info"));if("true"===a.infodetail)return h(errHndl.getErrMsg("EMPTY_VALUE","info-detail"));e=a.info?a.info:a.infodetail;c=path.resolve(__dirname,"../files/conf/ipk.json");if(".ipk"!==path.extname(e))return h(errHndl.getErrMsg("SUPPORT_ONLY_IPK",e));if(!fs.existsSync(e))return h(errHndl.getErrMsg("NOT_EXIST_PATH",
e));if(!fs.existsSync(c))return h(errHndl.getErrMsg("NOT_EXIST_PATH",c));d=JSON.parse(fs.readFileSync(c));g=temp.path(d.tmpPath);fs.existsSync(g)||fs.mkdirSync(g);h()},function(h){log.info("package#analyzeIPK()#_unpackIpk()");const l=new ar.ArReader(e);l.on("entry",function(m,q){const p=m.fileName();m.fileData().pipe(fs.createWriteStream(path.resolve(g,p))).on("finish",q)});l.on("error",function(m){return h(m)});l.on("close",function(){log.verbose("package#analyzeIPK()#_unpackIpk()","unpack ipk close");
h()})},function(h){log.info("package#analyzeIPK()#_unpackTar()");if(fs.existsSync(path.resolve(g,"control.tar.gz")))(function(){return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){yield decompress(path.resolve(g,"control.tar.gz"),g,{plugins:[decompressTargz()]});log.verbose("package#analyzeIPK()#_unpackTar()","control.tar.gz decompressed")})})();else return fs.existsSync(path.resolve(g,"control.tar.xz"))?h(errHndl.getErrMsg("NOT_SUPPORT_XZ")):h(errHndl.getErrMsg("NO_COMPONENT_FILE",", control tar file"));
if(fs.existsSync(path.resolve(g,"data.tar.gz")))(function(){return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){yield decompress(path.resolve(g,"data.tar.gz"),g,{plugins:[decompressTargz()]});log.verbose("package#analyzeIPK()#_unpackTar()","data.tar.gz decompressed");h()})})();else return fs.existsSync(path.resolve(g,"data.tar.xz"))?h(errHndl.getErrMsg("NOT_SUPPORT_XZ")):h(errHndl.getErrMsg("NO_COMPONENT_FILE","data tar file"))},function(h){log.info("package#analyzeIPK()#_analyzeMetaFile()");
let l="",m,q;d.webOSMetaFiles.forEach(function(p){const v=path.resolve(g,d[p].path);if("control"===p){m=path.resolve(v,d[p].fileName);if(!fs.existsSync(m))return h(errHndl.getErrMsg("NO_COMPONENT_FILE","control file"));a.infodetail?(l="\n\n< "+d[p].fileName+" >\n",l+=fs.readFileSync(m).toString().trim()):(l=d[p].heading+"\n",q=fs.readFileSync(m).toString().trim(),d[p].info.forEach(function(r){q.match(new RegExp(r+": (.*)","gi"))&&(l+=q.match(new RegExp(r+": (.*)","gi"))[0]+"\n")}))}else if(fs.existsSync(v)){const r=
fs.readdirSync(v);let x=r[0];r.forEach(function(w){d[p].fileName&&d[p].fileName.forEach(function(z){m=path.resolve(v,w,z);if(fs.existsSync(m))if(a.infodetail)l+="\n\n< "+z+" >\n",l+=fs.readFileSync(m).toString().trim();else{d[p].heading&&x!==path.join(d[p].path,w)&&(l+="\n"+d[p].heading+"\n");q=fs.readFileSync(m).toString().trim();const A=JSON.parse(q);d[p].info.forEach(function(B){if(A[B]){const D=A[B];if("object"===typeof D)if(d[p][B]){const F=d[p][B],G=[];D.forEach(function(J){G.push(J[F])});l+=
B+": "+JSON.stringify(G)+"\n"}else l+=B+": "+JSON.stringify(D)+"\n";else l+=B+": "+D+"\n"}});x=path.join(d[p].path,w)}})})}});h(null,l)},function(h){log.info("package#analyzeIPK()#_removeTmpDir()");rimraf(g,function(l){log.verbose("package#analyzeIPK()#_removeTmpDir()","removed "+g);h(l)})}],function(h,l){log.silly("package#analyzeIPK()","err:",h,", results:",l);return h?b(h):b(null,{msg:l[3].trim()})})}}})();
