const fs=require("fs"),path=require("path"),util=require("util"),stream=require("stream"),net=require("net"),mkdirp=require("mkdirp"),async=require("async"),log=require("npmlog"),Ssh2=require("ssh2"),shelljs=require("shelljs"),request=require("request"),server=require("./server"),errHndl=require("./error-handler"),Appdata=require("./cli-appdata");
(function(){function t(a,b,c){let d=null;return 0!==b||c?(d=Error(),d.message="Command '"+a+"' exited with code="+b+" (signal: "+c+")",d.code=b,errHndl.getErrMsg(d)):d}function u(){this.devices=[];this.deviceFileContent=null;q=new Appdata}const r={};"undefined"!==typeof module&&module.exports&&(module.exports=r);log.heading="novacom";log.level="warn";r.log=log;const n=path.resolve(process.env.HOME||process.env.USERPROFILE,".ssh");let q;r.Resolver=u;r.Resolver.prototype={load:function(a){const b=this;
log.verbose("Resolver#load()");async.waterfall([function(c){log.silly("Resolver#load#_replaceBuiltinSshKey()");const d=path.join(__dirname,"../../files/conf/","webos_emul"),e=path.join(n,"webos_emul");fs.stat(d,function(g,f){g?"ENOENT"===g.code?setImmediate(c):setImmediate(c,g):fs.stat(e,function(h,k){h?"ENOENT"===h.code?mkdirp(n,function(){shelljs.cp("-rf",d,n);fs.chmodSync(e,"0600");setImmediate(c)}):setImmediate(c,h):(f.mtime.getTime()>k.mtime.getTime()&&(shelljs.cp("-rf",d,n),fs.chmodSync(e,"0600")),
setImmediate(c))})})}.bind(b),function(c){log.silly("Resolver#load#_adjustList()");let d=q.getDeviceList(!0);1>d.filter(function(e){return void 0!==e.default}).length&&(log.silly("Resolver#load#_adjustList()","rewrite default field"),d=d.map(function(e){e.default="emulator"===e.name?!0:!1;return e}),this.save(d));setImmediate(c)}.bind(b),function(c){log.silly("Resolver#load#_loadString()");const d=q.getDeviceList(!0);Array.isArray(d)?async.forEach(d,function(e,g){async.series([b._loadOne.bind(b,e),
b._addOne.bind(b,e)],g)},function(e){e?setImmediate(c,e):setImmediate(c)}):setImmediate(c,errHndl.getErrMsg("INVALID_FILE"))}.bind(b)],function(c){c?setImmediate(a,c):setImmediate(a)})},_loadOne:function(a,b){log.silly("Resolver#_loadOne()");"string"===typeof a.privateKey?(a.privateKeyName=a.privateKey,a.privateKey=Buffer.from(a.privateKey,"base64"),setImmediate(b)):"object"===typeof a.privateKey&&"string"===typeof a.privateKey.openSsh?(a.privateKeyName=a.privateKey.openSsh,async.waterfall([fs.readFile.bind(this,
path.join(n,a.privateKey.openSsh),b),function(c,d){a.privateKey=c;setImmediate(d)}],function(c){c&&(log.verbose("Resolver#_loadOne()","Unable to find SSH private key named '"+a.privateKey.openSsh+"' from '"+n+" for '"+a.name+"'"),a.privateKey=void 0);setImmediate(b)})):"webospro"===a.type?setImmediate(b,errHndl.getErrMsg("NOT_IMPLEMENTED","webOS Pro device type handling")):(a.password||log.verbose("Resolver#_loadOne()","Regist privateKey : need to set a SSH private key in "+n+" for'"+a.name+"'"),
a.privateKeyName=void 0,a.privateKey=void 0,setImmediate(b))},_addOne:function(a,b){a.display={name:a.name,type:a.type,privateKeyName:a.privateKeyName,passphrase:a.passphrase,description:a.description,conn:a.conn||["ssh"],devId:a.id||null};a.username&&a.host&&a.port&&(a.display.addr="ssh://"+a.username+"@"+a.host+":"+a.port);for(var c in a)"display"!==c&&(a.display[c]=a[c]);log.silly("Resolver#_addOne()");this.devices=this.devices.filter(function(d){return d.name!==a.name});c=q.getCommandService();
a.lunaSend=c[a.type].lunaSend;a.lunaAddr=c[a.type].lunaAddr;this.devices.push(a);setImmediate(b)},save:function(a,b){log.verbose("Resolver#save()");log.silly("Resolver#save()","devicesData:",a);return q.setDeviceList(a,b)},list:function(a){log.verbose("Resolver#list()");setImmediate(a,null,this.devices.map(function(b){return b.display}))},setTargetName:function(a,b){a="string"===typeof a?a:a&&a.name;if(!a){a=this.devices.filter(function(c){return c.conn&&-1!==c.conn.indexOf("novacom")});if(1<a.length)return b(errHndl.getErrMsg("CONNECTED_MULTI_DEVICE"));
if(0<a.length&&a[0].name)a=a[0].name;else{a=this.devices.filter(function(c){return c.default&&!0===c.default});if(1<a.length)return b(errHndl.getErrMsg("SET_DEFAULT_MULTI_DEVICE"));a=1===a.length?a[0].name:"emulator"}}b(null,"name",a)},getDeviceBy:function(a,b,c){log.verbose("Resolver#getDeviceBy()","key:",a,", value:",b);const d=this.devices.filter(function(e){return e[a]&&e[a]===b});if(1>d.length)setImmediate(c,errHndl.getErrMsg("UNMATCHED_DEVICE",a,b));else if("function"===typeof c)log.silly("Resolver#getDeviceBy()",
"async"),setImmediate(c,null,d[0]);else return log.silly("Resolver#getDeviceBy()","sync"),d[0]},getSshPrvKey:function(a,b){var c="string"===typeof a?a:a&&a.name;if(!c){c=this.devices.filter(function(d){return d.default&&!0===d.default});if(1<c.length)return b(errHndl.getErrMsg("SET_DEFAULT_MULTI_DEVICE"));c=1===c.length?c[0].name:"emulator";"string"===typeof a?a=c:"object"===typeof a&&(a.name=c)}async.waterfall([this.getDeviceBy.bind(this,"name",c),function(d,e){log.info("Resolver#getSshPrvKey()",
"targetDevice.host:",d.host);const g="http://"+d.host+":9991/webos_rsa",f=d.name.replace(/(\s+)/gi,"_")+"_webos",h=path.join(n,f);request.head(g,function(k,m){if(k||m&&200!==m.statusCode)return setImmediate(e,errHndl.getErrMsg("FAILED_GET_SSHKEY"));log.info("Resolver#getSshPrvKey()#head","content-type:",m.headers["content-type"]);log.info("Resolver#getSshPrvKey()#head","content-length:",m.headers["content-length"]);request(g).pipe(fs.createWriteStream(h)).on("close",function(l){if(l)return setImmediate(e,
errHndl.getErrMsg("FAILED_GET_SSHKEY"));setImmediate(e,l,h,f)})})},function(d,e,g){log.info("Resolver#getSshPrvKey()","SSH Private Key:",d);console.log("SSH Private Key:",d);fs.chmodSync(d,"0600");setImmediate(g,null,e)}],b)},modifyDeviceFile:function(a,b,c){let d=q.getDeviceList(!0),e="emulator";log.verbose("modifyDeviceFile():","op:",a);log.verbose("modifyDeviceFile():","targt:",b);if(!b.name)return setImmediate(c,errHndl.getErrMsg("EMPTY_VALUE","target"));if(!Array.isArray(d))return setImmediate(c,
errHndl.getErrMsg("INVALID_FILE"));const g=d.filter(function(f){let h=!1;b.name===f.name&&(b.profile?b.profile===f.profile&&(h=!0):h=!0);return h});log.verbose("modifyDeviceFile():","matchedDevices:",g);if("add"===a){if(0<g.length)return setImmediate(c,errHndl.getErrMsg("EXISTING_VALUE","DEVICE_NAME",b.name));for(const f in b)"@DELETE@"===b[f]&&delete b[f];!0===b.default?e=b.name:!1===b.default&&(e=null);d=d.concat(b)}else if("remove"===a||"modify"===a||"default"===a){if(0===g.length)return setImmediate(c,
errHndl.getErrMsg("INVALID_VALUE","DEVICE_NAME",b.name));if("remove"===a){let f=null;d=d.filter(function(h){if(b.name===h.name){if(!0===h.indelible)return f=h.name,!0;!1===h.default&&(e=null);return!1}return!0});if(f)return setImmediate(c,errHndl.getErrMsg("CANNOT_REMOVE_DEVICE",f))}else"modify"===a?d=d.map(function(f){if(b.name===f.name){e=!0===f.default?f.name:null;for(const h in b)Object.prototype.hasOwnProperty.call(b,h)&&(f[h]=b[h],"@DELETE@"===f[h]&&delete f[h])}return f}):"default"===a&&d.map(function(f){b.name===
f.name&&!0===b.default&&(e=b.name)})}else return setImmediate(c,errHndl.getErrMsg("UNKNOWN_OPERATOR",a));null!=e&&(d=d.map(function(f){f.default=e===f.name?!0:!1;return f}));this.save(d,c)}};r.Session=function(a,b){if("function"!==typeof b)throw errHndl.getErrMsg("MISSING_CALLBACK","next",util.inspect(b));log.info("novacom.Session()","opening session to '"+("string"===typeof a?a:a&&a.name)+"'");this.resolver=new u;async.waterfall([this.resolver.load.bind(this.resolver),this.resolver.setTargetName.bind(this.resolver,
a),this.resolver.getDeviceBy.bind(this.resolver),this.checkConnection.bind(this),this.begin.bind(this)],b)};r.Session.prototype={checkConnection:function(a,b){let c=!1;if(a&&a.host&&a.port){const d=new net.Socket;d.setTimeout(2E3);const e=d.connect({host:a.host,port:a.port});e.on("connect",function(){c=!0;e.end();setImmediate(b,null,a)});e.on("error",function(g){e.destroy();setImmediate(b,errHndl.getErrMsg(g))});e.on("timeout",function(){e.destroy();c||setImmediate(b,errHndl.getErrMsg("TIME_OUT"))})}else setImmediate(b,
null,a)},begin:function(a,b){function c(g){setImmediate(b,g?errHndl.getErrMsg(g):g,this)}function d(){log.verbose("Clear Session");e.end();setTimeout(function(){process.exit()},500)}log.verbose("Session#begin()","target:",a.display);const e=this;this.target=a||this.target;if(this.target.conn&&-1===this.target.conn.indexOf("ssh"))return setImmediate(b,null,this),this;this.ssh||(this.forwardedPorts=[],this.ssh=new Ssh2,this.ssh.on("connect",function(){log.verbose("Session#begin()","ssh session event: connected")}),
this.ssh.on("ready",c.bind(this)),this.ssh.on("error",c.bind(this)),this.ssh.on("end",function(){log.verbose("Session#begin()","ssh session event: end")}),this.ssh.on("close",function(g){log.verbose("Session#begin()","ssh session event: close (had_error:",g,")")}),this.target.readyTimeout=3E4,this.ssh.connect(this.target),process.on("SIGHUP",d),process.on("SIGINT",d),process.on("SIGQUIT",d),process.on("SIGTERM",d),process.on("exit",function(){d()}));return this},getDevice:function(){return this.target},
end:function(){log.verbose("Session#end()");this.ssh&&this.ssh.end();return this},_checkSftp:function(a){this.ssh.subsys("sftp",function(b,c){if(b)return setImmediate(a,b);c.once("data",function(d){if(d.toString().match(RegExp("sftp-server(.| )+not found","gi")))return d=errHndl.getErrMsg("UNABLE_USE_SFTP"),d.code=4,setImmediate(a,d)})})},put:function(a,b,c){log.verbose("Session#put()","uploding into device:",b,"from host:",a);let d;const e=this;log.verbose("Session#put()","sftpPut() :: start");e.sftpPut(a,
b,function(g){g?(log.verbose(g),4===g.code||127===g.code?(log.verbose("Session#put()","sftp is not available, attempt transfering file via streamPut"),d=fs.createReadStream(a),e.streamPut(b,d,c)):14===g.code?(g=errHndl.getErrMsg("NO_FREE_SPACE"),setImmediate(c,g)):setImmediate(c,g)):(log.verbose("Session#put()","sftpPut() :: done"),setImmediate(c))})},streamPut:function(a,b,c){log.verbose("Session#streamPut()","streaming into device:"+a);this.run('/bin/cat > "'+a+'"',b,null,process.stderr,c)},sftpPut:function(a,
b,c){log.verbose("Session#sftpPut()","host:"+a+" => device:"+b);const d=this;d._checkSftp(c);async.series({transfer:function(e){d.ssh.sftp(function(g,f){if(g)return setImmediate(e,g);const h=fs.createReadStream(a),k=f.createWriteStream(b);k.on("close",function(){f.end();setImmediate(e)});k.on("exit",function(m,l){g=t("sftpPut",m,l);setImmediate(e,g)});k.on("error",function(m){log.verbose("Session#sftpPut()","error:",m);setImmediate(e,m)});h.pipe(k)})}},function(e){setImmediate(c,e)})},run:function(a,
b,c,d,e){this.run_ssh(a,b,c,d,e)},run_ssh:function(a,b,c,d,e){log.verbose("Session#run()","running");if("function"!==typeof e)throw errHndl.getErrMsg("MISSING_CALLBACK","next",util.inspect(e));const g={},f={};c?c instanceof stream.Stream?(log.silly("Session#run()","stdout: stream"),g.stdout=c.write,f.stdout=c):c instanceof Function?(log.silly("Session#run()","stdout: function"),g.stdout=c):setImmediate(e,errHndl.getErrMsg("INVALID_VALUE","stdout",util.inspect(c))):(log.silly("Session#run()","stdout: none"),
g.stdout=function(){});d?d instanceof stream.Stream?(log.silly("Session#run()","stderr: stream"),g.stderr=d.write,f.stderr=d):d instanceof Function?(log.silly("Session#run()","stderr: function"),g.stderr=d):setImmediate(e,errHndl.getErrMsg("INVALID_VALUE","stderr",util.inspect(d))):(log.silly("Session#run()","stderr: none"),g.stderr=function(){});this.ssh.exec(a,function(h,k){log.silly("Session#run()","exec cmd");if(h)return log.verbose("Session#run()","exec err:"+h),setImmediate(e,h);k.on("data",
function(m,l){l=l||"stdout";log.silly("Session#run()","on data ("+l+")");g[l].bind(f[l])(m)}).stderr.on("data",function(m){log.silly("Session#run()","on data (stderr)");g.stderr.bind(f.stderr)(m)});k.on("end",function(){log.verbose("Session#run()","event end");c!==process.stdout&&c instanceof stream.Stream&&c.end();d!==process.stderr&&d instanceof stream.Stream&&d.end()});k.on("exit",function(m,l){log.verbose("Session#run()","event exit, code="+m+", signal="+l);h=t(a,m,l);setImmediate(e,h)});k.on("close",
function(){log.verbose("Session#run()","event close");void 0===h&&setImmediate(e)});b&&(b.pipe(k),log.silly("Session#run()","resuming input"))})},runNoHangup:function(a,b,c,d){this.runNoHangup_ssh(a,b,c,d)},runNoHangup_ssh:function(a,b,c,d){log.verbose("Session#runNoHangup()","cmd="+a);if(2>arguments.length)throw errHndl.getErrMsg("MISSING_CALLBACK","next");for(const e in arguments)"undefined"===typeof arguments[e]&&(delete arguments[e],arguments.length--);switch(arguments.length){case 2:d=b;b=c=
null;break;case 3:d=c,c=b,b=null}if("function"!==typeof d)throw errHndl.getErrMsg("MISSING_CALLBACK","next",util.inspect(d));this.ssh.exec(a,function(e,g){log.verbose("Session#run()","exec cmd: "+a+", err:"+e);if(e)return setImmediate(d,e);g.on("data",function(f){const h=Buffer.isBuffer(f)?f.toString():f;log.verbose("[Session#runNoHangup()#onData]",h);b&&b(f)}).stderr.on("data",function(f){const h=Buffer.isBuffer(f)?f.toString():f;log.verbose("Session#runNoHangup()#onData#stderr#",h);b&&b(f)});if(c)g.on("exit",
function(f,h){log.verbose("Session#runNoHangup()","event exit code="+f+", signal="+h+" (cmd: "+a+")");e=t(a,f,h);c(e)});setImmediate(d)})},forward:function(a,b,c,d){log.verbose("Session#forward()","devicePort:",a,"localPort:",b);const e=this;let g=!1,f=null;"function"===typeof c?d=c:c&&(f=c);0!==b?0<e.forwardedPorts.indexOf({name:f,local:b,device:a})&&(g=!0):0<e.forwardedPorts.filter(function(k){return k.device===a&&k.name===f}).length&&(g=!0);if(g)return setImmediate(d);const h=net.createServer(function(k){log.info("Session#forward()",
"new client, localPort:",b);log.verbose("Session#forward()","new client, from: "+k.remoteAddress+":"+k.remotePort);k.on("error",function(m){log.verbose("Session#forward()","inCnx::error, err:: "+m)});e.ssh.forwardOut("127.0.0.1",k.remotePort,"127.0.0.1",a,function(m,l){m?(console.log("Session#forward()","failed forwarding client localPort:",b,"(inCnx.remotePort:",k.remotePort,")=> devicePort:",a),log.warn("Session#forward()","failed forwarding client localPort:",b,"=> devicePort:",a),k.destroy()):
(log.info("Session#forward()","connected, devicePort:",a),k.on("data",function(p){l.writable&&!0===l.writable&&!1===l.write(p)&&k.pause()}),k.on("close",function(p){log.verbose("Session#forward()","inCnx::close, had_err:",p);l.destroy()}),l.on("drain",function(){k.resume()}),l.on("data",function(p){k.write(p)}),l.on("close",function(p){log.verbose("Session#forward()","outCnx::close, had_err:",p)}))})});e.ssh.on("close",function(){h.close()});try{h.listen(b,null,function(){const k=h.address().port;
e.forwardedPorts.push({name:f,local:k,device:a});setImmediate(d)})}catch(k){setImmediate(d,k)}},getLocalPortByName:function(a){let b=null;this.forwardedPorts.forEach(function(c){c.name===a&&(b=c.local)});return b},runHostedAppServer:function(a,b){server.runServer(a,0,function(c,d){d&&d.port&&this.setHostedAppServerPort(d.port);b(c)}.bind(this))},setHostedAppServerPort:function(a){this.hostedAppServerPort=a},getHostedAppServerPort:function(){return this.hostedAppServerPort}}})();
